### ISSUE TITLE
BetaCalcMc failed to skid hyperlethal ca?

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [IllegalException/xenon-database#1]
Hyperlethal's loader is obfuscated, Not too sure where the source of HyperLethal is unless opensource which is highly unlikely.

**Comment by XeonLyfe** [comment]
He wanted to skid it, then realized he can’t open it in winrar and then tried to find a leaked version of it, but then his chinese decompiler couldn’t decompile obfuscated code. Ngl i think it’s a skill issue

**Comment by Tarkan-Zarrouk** [comment]
> He wanted to skid it, then realized he can’t open it in winrar and then tried to find a leaked version of it, but then his chinese decompiler couldn’t decompile obfuscated code. Ngl i think it’s a skill issue

Well obviously he can't skid it itlmao, besides Spartan is using ESkid obfuscator which sorta fucks with new people lol
